import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Next App Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html className="dark" lang="en">
      <body className={poppins.className}>
        <main className="flex flex-col h-full p-5 bg-white dark:bg-slate-700">
          {/* <SearchBar /> */}
          {children}
        </main>
      </body>
    </html>
  );
}
